notifications:
  email: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"

env:
 - CC=gcc-5 SWIG=swig3.0

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-5
     - g++-5

before_install:
  # This should be 3.0.8 that solves a python 3.5 swig issue
  - sudo add-apt-repository ppa:nschloe/swig-backports -y
  #ppa:rosmo/swig3.0.7 -y
  - sudo apt-get -qq update
  - sudo apt-get install -y swig3.0

install:
  - pip install Cython
  - pip install numpy
  - pip install pysam
  - pip install matplotlib
  - bash ./build_it
 
script:
  - python test/test.py
