dist: trusty

sudo: required

notifications:
  email: false

language: python

python:
  - "2.7"

env:
 global:
  - SWIG=swig3.0
 matrix:
  - CC=gcc-5 PYSAM_VERSION='pysam==0.9.0' PYPI="-i https://testpypi.python.org/pypi"
  - CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="-i https://testpypi.python.org/pypi"
  - CC=gcc-5 PYSAM_VERSION='pysam' PYPI="-i https://testpypi.python.org/pypi"
  - CC=gcc PYSAM_VERSION='pysam' PYPI="-i https://testpypi.python.org/pypi"
  - CC=gcc-5 PYSAM_VERSION='pysam==0.9.0' PYPI=""
  - CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI=""
  - CC=gcc-5 PYSAM_VERSION='pysam' PYPI=""
  - CC=gcc PYSAM_VERSION='pysam' PYPI=""

addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-5
     - g++-5

before_install:
  - sudo add-apt-repository ppa:nschloe/swig-backports -y
  - sudo apt-get -qq update
  - sudo apt-get install -y swig3.0

install:
  - sed -i "s/pysam>=0.9.0/$PYSAM_VERSION/" requirements.txt
  - pip install -r requirements.txt
  - pip install $PYPI HTSeq
 
script:
  - python test/test.py
