notifications:
  email: false

language: python

env:
 global:
  - SWIG=swig3.0

matrix:
  include:
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI="https://test.pypi.org/pypi/"
      python: 2.7
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI="https://test.pypi.org/pypi/"
      python: 3.4
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI="https://test.pypi.org/pypi/"
      python: 3.5
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI="https://test.pypi.org/pypi/"
      python: 3.6
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.13.0' PYTHON_VERSION='2.7' PYPI="https://test.pypi.org/pypi/"
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.13.0' PYTHON_VERSION='3.6' PYPI="https://test.pypi.org/pypi/"
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI="https://test.pypi.org/pypi/"
      python: 2.7
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI="https://test.pypi.org/pypi/"
      python: 3.4
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI="https://test.pypi.org/pypi/"
      python: 3.5
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI="https://test.pypi.org/pypi/"
      python: 3.6
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYTHON_VERSION='2.7' PYPI="https://test.pypi.org/pypi/"
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYTHON_VERSION='3.6' PYPI="https://test.pypi.org/pypi/"
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="https://test.pypi.org/pypi/" CYTHON_INSTALL='Cython'
      python: 2.7
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="https://test.pypi.org/pypi/" CYTHON_INSTALL='Cython'
      python: 3.4
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="https://test.pypi.org/pypi/" CYTHON_INSTALL='Cython'
      python: 3.5
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="https://test.pypi.org/pypi/" CYTHON_INSTALL='Cython'
      python: 3.6
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYTHON_VERSION='2.7' PYPI="https://test.pypi.org/pypi/" CYTHON_INSTALL='Cython'
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYTHON_VERSION='3.6' PYPI="https://test.pypi.org/pypi/" CYTHON_INSTALL='Cython'
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI=""
      python: 2.7
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI=""
      python: 3.4
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI=""
      python: 3.5
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam' PYPI=""
      python: 3.6
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam' PYTHON_VERSION='2.7' PYPI=""
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam' PYTHON_VERSION='3.6' PYPI=""
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI=""
      python: 2.7
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI=""
      python: 3.4
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI=""
      python: 3.5
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYPI=""
      python: 3.6
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYTHON_VERSION='2.7' PYPI=""
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.10.0' PYTHON_VERSION='3.6' PYPI=""
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="" CYTHON_INSTALL='Cython'
      python: 2.7
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="" CYTHON_INSTALL='Cython'
      python: 3.4
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="" CYTHON_INSTALL='Cython'
      python: 3.5
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYPI="" CYTHON_INSTALL='Cython'
      python: 3.6
      os: linux
      dist: trusty
      sudo: required
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYTHON_VERSION='2.7' PYPI="" CYTHON_INSTALL='Cython'
      language: generic
      os: osx
    - env: CC=gcc PYSAM_VERSION='pysam==0.9.0' PYTHON_VERSION='3.6' PYPI="" CYTHON_INSTALL='Cython'
      language: generic
      os: osx

before_install:
  - ./.travis_before_install.sh

install:
  - ./.travis_install.sh
 
script:
  - ./.travis_test.sh

#after_success:
#  - ./.travis_deploy.sh
